# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LqoqJb1dBusQPqoD5BgwvzG91Xs8d_YX
"""

# ============================================
# 🔹 Single Unit Perceptron for Binary Classification
# ============================================

# Importing required libraries
import numpy as np                      # For numerical operations and array handling
import matplotlib.pyplot as plt          # For data visualization (plots and graphs)
from sklearn.datasets import make_classification  # To generate a synthetic dataset
from sklearn.linear_model import Perceptron       # Perceptron model from sklearn
from sklearn.metrics import accuracy_score        # To evaluate model performance

# ============================================
# Step 1: Generate a linearly separable dataset
# ============================================
X, y = make_classification(
    n_samples=100,       # Generate 100 data samples
    n_features=2,        # Each sample has 2 features (for 2D plotting)
    n_informative=1,     # Only 1 feature contributes to class separation
    n_redundant=0,       # No redundant (duplicate) features
    n_classes=2,         # Two output classes (binary classification)
    n_clusters_per_class=1,  # One cluster per class for clear separation
    class_sep=10,        # High separation to make the data linearly separable
    random_state=41,     # Fixing randomness for reproducibility
    hypercube=False      # Prevents data from forming a hypercube structure
)

# ============================================
# Step 2: Visualize the generated dataset
# ============================================
plt.figure(figsize=(8,6))                              # Set figure size for better visibility
plt.scatter(X[y==0][:,0], X[y==0][:,1], color='red', label='Class 0')   # Plot points for Class 0
plt.scatter(X[y==1][:,0], X[y==1][:,1], color='blue', label='Class 1')  # Plot points for Class 1
plt.title("Generated Linearly Separable Data")          # Title of the plot
plt.xlabel("Feature 1")                                # X-axis label
plt.ylabel("Feature 2")                                # Y-axis label
plt.legend()                                           # Show legend (class labels)
plt.show()                                             # Display the plot

# ============================================
# Step 3: Initialize and train the Perceptron
# ============================================
model = Perceptron(max_iter=1000, eta0=0.1, random_state=41)  # Create Perceptron with learning rate 0.1
model.fit(X, y)                                                # Train (fit) the perceptron model on data

# ============================================
# Step 4: Evaluate the model
# ============================================
y_pred = model.predict(X)                     # Predict class labels for training data
acc = accuracy_score(y, y_pred)               # Calculate accuracy score
print(f"Training Accuracy: {acc*100:.2f}%")   # Print the training accuracy percentage

# ============================================
# Step 5: Visualize the decision boundary
# ============================================
w = model.coef_[0]        # Extract learned weight vector (w1, w2)
b = model.intercept_[0]   # Extract learned bias term

# Define the range for the plot grid (mesh)
x_min, x_max = X[:,0].min() - 1, X[:,0].max() + 1   # X-axis limits
y_min, y_max = X[:,1].min() - 1, X[:,1].max() + 1   # Y-axis limits

# Create a mesh grid of (x, y) points to visualize decision regions
xx, yy = np.meshgrid(np.linspace(x_min, x_max, 200),
                     np.linspace(y_min, y_max, 200))

# Predict the class for each point in the grid
Z = model.predict(np.c_[xx.ravel(), yy.ravel()])  # Flatten grid and predict
Z = Z.reshape(xx.shape)                           # Reshape back to grid shape for plotting

# Plot the decision regions
plt.figure(figsize=(8,6))                         # Set figure size
plt.contourf(xx, yy, Z, alpha=0.3, cmap=plt.cm.bwr)  # Fill regions by predicted class
plt.scatter(X[y==0][:,0], X[y==0][:,1], color='red', label='Class 0')   # Plot original data (Class 0)
plt.scatter(X[y==1][:,0], X[y==1][:,1], color='blue', label='Class 1')  # Plot original data (Class 1)

# Plot the decision boundary line: w1*x1 + w2*x2 + b = 0  →  x2 = -(w1*x1 + b)/w2
x_points = np.linspace(x_min, x_max, 100)              # Generate x-values for the line
y_points = -(w[0] * x_points + b) / w[1]               # Calculate corresponding y-values
plt.plot(x_points, y_points, color='black', linewidth=2, label='Decision Boundary')  # Plot the line

plt.title("Perceptron Decision Boundary")              # Title for the decision boundary plot
plt.xlabel("Feature 1")                                # X-axis label
plt.ylabel("Feature 2")                                # Y-axis label
plt.legend()                                           # Show class and boundary legend
plt.show()                                             # Display the final plot